# Generated by Django 2.2.19 on 2022-05-29 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_follow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='post',
            new_name='user',
        ),
    ]
