# Generated by Django 2.2.19 on 2022-05-29 14:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20220529_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='user',
            field=models.ForeignKey(on_delete=None, related_name='follower', to=settings.AUTH_USER_MODEL),
        ),
    ]
